// ============================================================================
// OFFLINE QUEUE MANAGER
// ============================================================================
// File: lib/offline/queue.ts
// Description: Manages offline mutations and syncs when online
// Version: 1.0
// Date: 2026-05-08
// ============================================================================

import {
  addToStore,
  updateInStore,
  getAllFromStore,
  deleteFromStore,
  queryByIndex,
  STORES,
} from './indexeddb';

/**
 * Queue item status
 */
export type QueueStatus = 'pending' | 'syncing' | 'synced' | 'failed';

/**
 * Queue item type
 */
export type QueueItemType = 'transaction' | 'inventory' | 'production' | 'other';

/**
 * Offline queue item
 */
export interface OfflineQueueItem {
  id?: number; // Auto-generated by IndexedDB
  type: QueueItemType;
  action: string; // e.g., 'create_order', 'update_stock'
  data: any; // The mutation data
  timestamp: number;
  status: QueueStatus;
  retryCount: number;
  lastError?: string;
  metadata?: {
    outletId?: string;
    userId?: string;
    [key: string]: any;
  };
}

/**
 * Add item to offline queue
 */
export async function addToQueue(
  type: QueueItemType,
  action: string,
  data: any,
  metadata?: OfflineQueueItem['metadata']
): Promise<number> {
  const item: OfflineQueueItem = {
    type,
    action,
    data,
    timestamp: Date.now(),
    status: 'pending',
    retryCount: 0,
    metadata,
  };

  const id = await addToStore(STORES.OFFLINE_QUEUE, item);
  console.log(`📥 Added to offline queue: ${action} (ID: ${id})`);
  return id as number;
}

/**
 * Get all pending queue items
 */
export async function getPendingQueueItems(): Promise<OfflineQueueItem[]> {
  try {
    const items = await queryByIndex<OfflineQueueItem>(
      STORES.OFFLINE_QUEUE,
      'status',
      'pending'
    );
    return items.sort((a, b) => a.timestamp - b.timestamp);
  } catch (error) {
    console.error('Failed to get pending queue items:', error);
    return [];
  }
}

/**
 * Get all queue items
 */
export async function getAllQueueItems(): Promise<OfflineQueueItem[]> {
  try {
    const items = await getAllFromStore<OfflineQueueItem>(STORES.OFFLINE_QUEUE);
    return items.sort((a, b) => a.timestamp - b.timestamp);
  } catch (error) {
    console.error('Failed to get all queue items:', error);
    return [];
  }
}

/**
 * Update queue item status
 */
export async function updateQueueItem(
  item: OfflineQueueItem
): Promise<void> {
  if (!item.id) {
    throw new Error('Queue item must have an ID to update');
  }
  await updateInStore(STORES.OFFLINE_QUEUE, item);
}

/**
 * Mark queue item as synced and remove it
 */
export async function markAsSynced(itemId: number): Promise<void> {
  await deleteFromStore(STORES.OFFLINE_QUEUE, itemId);
  console.log(`✅ Queue item ${itemId} synced and removed`);
}

/**
 * Mark queue item as failed
 */
export async function markAsFailed(
  item: OfflineQueueItem,
  error: string
): Promise<void> {
  if (!item.id) return;

  item.status = 'failed';
  item.lastError = error;
  item.retryCount += 1;

  await updateInStore(STORES.OFFLINE_QUEUE, item);
  console.error(`❌ Queue item ${item.id} failed:`, error);
}

/**
 * Retry failed queue items
 */
export async function retryFailedItems(): Promise<void> {
  try {
    const failedItems = await queryByIndex<OfflineQueueItem>(
      STORES.OFFLINE_QUEUE,
      'status',
      'failed'
    );

    for (const item of failedItems) {
      if (item.retryCount < 3) {
        // Max 3 retries
        item.status = 'pending';
        await updateInStore(STORES.OFFLINE_QUEUE, item);
        console.log(`🔄 Retrying queue item ${item.id}`);
      }
    }
  } catch (error) {
    console.error('Failed to retry failed items:', error);
  }
}

/**
 * Clear all synced items from queue
 */
export async function clearSyncedItems(): Promise<void> {
  try {
    const syncedItems = await queryByIndex<OfflineQueueItem>(
      STORES.OFFLINE_QUEUE,
      'status',
      'synced'
    );

    for (const item of syncedItems) {
      if (item.id) {
        await deleteFromStore(STORES.OFFLINE_QUEUE, item.id);
      }
    }

    console.log(`🗑️ Cleared ${syncedItems.length} synced items`);
  } catch (error) {
    console.error('Failed to clear synced items:', error);
  }
}

/**
 * Get queue statistics
 */
export async function getQueueStats(): Promise<{
  total: number;
  pending: number;
  syncing: number;
  synced: number;
  failed: number;
}> {
  try {
    const items = await getAllQueueItems();

    return {
      total: items.length,
      pending: items.filter((i) => i.status === 'pending').length,
      syncing: items.filter((i) => i.status === 'syncing').length,
      synced: items.filter((i) => i.status === 'synced').length,
      failed: items.filter((i) => i.status === 'failed').length,
    };
  } catch (error) {
    console.error('Failed to get queue stats:', error);
    return { total: 0, pending: 0, syncing: 0, synced: 0, failed: 0 };
  }
}
